# Generated by Django 4.1 on 2023-04-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Live',
        ),
    ]
