# Generated by Django 4.1 on 2022-08-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Streamers',
            new_name='Streamer',
        ),
    ]
