# Generated by Django 4.1 on 2022-08-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_rename_streamers_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='youtube',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
