# Generated by Django 4.1 on 2022-08-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_streamer_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer',
            old_name='others',
            new_name='other',
        ),
    ]
