# Generated by Django 4.1 on 2023-04-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0006_streamer_color_streamer_discord_streamer_pourcent1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='color',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='equipe',
            name='discord',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='equipe',
            name='pourcent1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='equipe',
            name='pourcent2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='equipe',
            name='pourcent3',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='equipe',
            name='skill1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='equipe',
            name='skill2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='equipe',
            name='skill3',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
