# Generated by Django 4.1 on 2023-08-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0007_equipe_color_equipe_discord_equipe_pourcent1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='ordre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
