# Generated by Django 4.1 on 2024-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipe", "0008_equipe_ordre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("twitch", models.CharField(blank=True, max_length=256)),
                ("youtube", models.CharField(blank=True, max_length=256)),
                ("twitter", models.CharField(blank=True, max_length=256)),
                ("instagram", models.CharField(blank=True, max_length=256)),
                ("tiktok", models.CharField(blank=True, max_length=256)),
                ("discord", models.CharField(blank=True, max_length=256)),
                ("other", models.CharField(blank=True, max_length=256)),
                ("pp", models.ImageField(blank=True, null=True, upload_to="streamers")),
                ("color", models.CharField(blank=True, max_length=256)),
                ("skill1", models.CharField(blank=True, max_length=256)),
                ("pourcent1", models.CharField(blank=True, max_length=256)),
                ("skill2", models.CharField(blank=True, max_length=256)),
                ("pourcent2", models.CharField(blank=True, max_length=256)),
                ("skill3", models.CharField(blank=True, max_length=256)),
                ("pourcent3", models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
