# Generated by Django 4.1 on 2024-08-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0009_intervenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='facebook',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='facebook',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='streamer',
            name='facebook',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
