# Generated by Django 4.1 on 2022-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='pp',
            field=models.ImageField(blank=True, null=True, upload_to='partenaires'),
        ),
    ]
