# Generated by Django 4.1 on 2023-04-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaire', '0002_alter_partenaire_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='discord',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='instagram',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='other',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='tiktok',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='twitch',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='twitter',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='youtube',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
