# Generated by Django 4.1 on 2023-08-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('schedule', models.CharField(max_length=64)),
                ('hashtag', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('pp', models.ImageField(blank=True, null=True, upload_to='emissions')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.categorie')),
            ],
        ),
    ]
