# Generated by Django 4.1 on 2023-08-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='color',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
